apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: chain-ndl
resources:
  - pvc.yaml
  - service.yaml
  - nethermind.yaml
  - lighthouse.yaml
  - namespace.yaml
  - mev-boost.yaml
configMapGenerator:
  - name: nethermind-jwt
    files: ["jwt.hex"]
    options:
      disableNameSuffixHash: true
images:
  - name: nethermind/nethermind
    newTag: 1.17.0
  - name: sigp/lighthouse
    newTag: v3.4.0