apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: chain-ndl
resources:
  - pvc.yaml
  - service.yaml
  - nethermind.yaml
  - lighthouse.yaml
  - namespace.yaml
configMapGenerator:
  - name: nethermind-jwt
    files: ["jwt.hex"]
    options:
      disableNameSuffixHash: true
images:
  - name: ethereum/client-go
    newTag: v1.10.23
  - name: gcr.io/prysmaticlabs/prysm/beacon-chain
    newTag: v3.1.1