apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nethermind
  namespace: chain-ndl
spec:
  selector:
    matchLabels:
      app: nethermind
  replicas: 1
  serviceName: nethermind
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nethermind
    spec:
      terminationGracePeriodSeconds: 300
      containers:
        - name: nethermind
          image: nethermind/nethermind
          ports:
            - containerPort: 8545
            - containerPort: 8551
            - { containerPort: 30303, protocol: TCP }
            - { containerPort: 30303, protocol: UDP }
          args:
            [
                "--config=goerli",
                "--datadir=data",
                "--HealthChecks.Enabled=true",
                "--JsonRpc.Enabled=true",
                '--JsonRpc.JwtSecretFile="/root/jwt/jwt.hex"',
                "--JsonRpc.EngineHost=0.0.0.0",
                "--JsonRpc.EnginePort=8551",
                "--JsonRpc.Host=0.0.0.0",
                "--JsonRpc.Port=8545",
                "--purge-db",
                "--Sync.SnapSync=true",
                "--Sync.AncientBodiesBarrier=4367322",
                "--Sync.AncientReceiptsBarrier=4367322"
            ]
          resources:
            requests:
              memory: 2G
              cpu: 1000m
            limits:
              memory: 16G
              cpu: 8000m
          livenessProbe:
            httpGet:
              path: /
              port: 8545
          readinessProbe:
            httpGet:
              path: /
              port: 8545
          volumeMounts:
            - name: chaindata
              mountPath: /nethermind/data
            - name: jwt
              mountPath: /root/jwt

      volumes:
        - name: chaindata
          persistentVolumeClaim:
            claimName: chaindata-nethermind
        - configMap:
            name: nethermind-jwt
          name: jwt
