apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nethermind
  namespace: besu-teku
spec:
  selector:
    matchLabels:
      app: nethermind
  replicas: 1
  serviceName: nethermind
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nethermind
    spec:
      terminationGracePeriodSeconds: 300
      securityContext:
        fsGroup: 0
        runAsUser: 0
        runAsGroup: 0
      containers:
        - name: nethermind
          image: nethermind/nethermind:1.15.0
          ports:
            - containerPort: 8545
            - containerPort: 8551
            - { containerPort: 30303, protocol: TCP }
            - { containerPort: 30303, protocol: UDP }
          args:
            [
                "--config=goerli",
                "--log=INFO",
                "--datadir=data",
                "--HealthChecks.Enabled=true",
                "--JsonRpc.Enabled=true",
                '--JsonRpc.JwtSecretFile="/root/jwt/jwt.hex"',
                '--JsonRpc.EnabledModules=["Eth", "Subscribe", "Trace", "TxPool", "Web3", "Personal", "Proof", "Net", "Parity", "Health"]',
                "--JsonRpc.Host=0.0.0.0",
                "--JsonRpc.Port=8545",
                "--Sync.SnapSync=true",
                "--Sync.AncientBodiesBarrier=4367322",
                "--Sync.AncientReceiptsBarrier=4367322"
            ]
          resources:
            requests:
              memory: 2G
              cpu: 1000m
            limits:
              memory: 16G
              cpu: 8000m
          livenessProbe:
            httpGet:
              path: /
              port: 8545
          readinessProbe:
            httpGet:
              path: /
              port: 8545
          volumeMounts:
            - name: chaindatan
              mountPath: /nethermind/data
            - name: jwt
              mountPath: /root/jwt
        - name: beacon
          image: consensys/teku
          args:
            - --network=goerli                             
            - --ee-endpoint=http://localhost:8551          
            - --ee-jwt-secret-file=/root/jwt.hex
            - --metrics-enabled=true                       
            - --rest-api-enabled=true
            - --data-path=/opt/app/beacon/

          ports:
            - containerPort: 5052
              name: http-api
            - containerPort: 5054
              name: metrics
            - containerPort: 9000
              name: p2ptcp
            - containerPort: 9000
              protocol: UDP
              name: p2pudp
          readinessProbe:
            tcpSocket:
              port: 9000
          livenessProbe:
            tcpSocket:
              port: 9000
          startupProbe:
            failureThreshold: 60
            tcpSocket:
              port: 9000
          resources:
            limits:
              cpu: 8000m
              memory: 16G
            requests:
              cpu: 1000m
              memory: 4G
          volumeMounts:
            - mountPath: /opt/app/beacon/
              name: chaindata
            - mountPath: /root/
              name: jwt  

      volumes:
        - name: chaindatan
          persistentVolumeClaim:
            claimName: chaindata-nethermind
        - name: chaindata
          persistentVolumeClaim:
            claimName: chaindata-teku
        - configMap:
            name: besu-jwt
          name: jwt
