apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: teku
spec:
  selector:
    matchLabels:
      app: teku
  serviceName: teku
  template:
    metadata:
      labels:
        app: teku
    spec:
      terminationGracePeriodSeconds: 300
      securityContext:
        fsGroup: 0
        runAsUser: 0
        runAsGroup: 0
      containers:
        - name: beacon
          image: consensys/teku
          args:
            - --network=goerli                             
            - --ee-endpoint=http://nethermind.besu-teku.svc.cluster.local:8551          
            - --ee-jwt-secret-file=/root/jwt.hex
            - --metrics-enabled=true                       
            - --rest-api-enabled=true
            - --data-path=/opt/app/beacon/

          ports:
            - containerPort: 5052
              name: http-api
            - containerPort: 5054
              name: metrics
            - containerPort: 9000
              name: p2ptcp
            - containerPort: 9000
              protocol: UDP
              name: p2pudp
          readinessProbe:
            tcpSocket:
              port: 9000
          livenessProbe:
            tcpSocket:
              port: 9000
          startupProbe:
            failureThreshold: 60
            tcpSocket:
              port: 9000
          resources:
            limits:
              cpu: 8000m
              memory: 16G
            requests:
              cpu: 1000m
              memory: 4G
          volumeMounts:
            - mountPath: /opt/app/beacon/
              name: chaindata
            - mountPath: /root/
              name: jwt
      volumes:
        - name: chaindata
          persistentVolumeClaim:
            claimName: chaindata-teku
        - configMap:
            name: besu-jwt
          name: jwt
