apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chaindata-teku
spec:
  resources:
    requests:
      storage: 1024Gi
  volumeMode: Filesystem
  storageClassName: csi-gcs
  accessModes:
    - ReadWriteOnce