---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goerli-erigon
  namespace: ergion-lighthouse-ceph-block
spec:
  selector:
    matchLabels:
      app: goerli-erigon
  revisionHistoryLimit: 0
  replicas: 1
  template:
    metadata:
      labels:
        app: goerli-erigon
    spec:
      shareProcessNamespace: true
      initContainers:
        - name: chown
          image: busybox
          command:
            - chown
            - -R
            - "1000:1000"
            - /home/erigon/goerli
          volumeMounts:
            - mountPath: /home/erigon/goerli
              name: goerli-erigon-data
      containers:
        - name: goerli-erigon
          securityContext:
            readOnlyRootFilesystem: true
            runAsUser: 1000
          resources:
            requests:
              memory: 6Gi
              cpu: 2000m
            limits:
              memory: 8Gi
              cpu: 3000m
          command: [
            "erigon",
            "--datadir=/home/erigon/goerli",
            "--chain=goerli",
            "--metrics",
            "--metrics.addr=0.0.0.0",
            "--metrics.port=6060",
            "--private.api.addr=localhost:9090",
            "--pprof",
            "--pprof.addr=0.0.0.0",
            "--pprof.port=6061",
            "--authrpc.jwtsecret=/data/jwt.hex"
          ]
          image: thorax/erigon
          ports:
            - containerPort: 30303
            - containerPort: 6060
            - containerPort: 6061
            - containerPort: 9090
          volumeMounts:
            - mountPath: /home/erigon/goerli
              name: goerli-erigon-data
            - mountPath: /tmp
              name: tmp
            - mountPath: /data
              name: erigon-jwt
      restartPolicy: Always
      volumes:
        - name: goerli-erigon-data
          persistentVolumeClaim:
            claimName: erigon-node-pvc
        - name: erigon-jwt
          configMap:
            name: erigon-jwt
        - name: tmp
          emptyDir: {}