apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: besu-teku
resources:
  - pvc.yaml
  - service.yaml
  - erigon.yaml
  - lighthouse.yaml
  - namespace.yaml
  - mev-boost.yaml
  - pool.yaml

configMapGenerator:
  - name: erigon-jwt
    files: ["jwt.hex"]
    options:
      disableNameSuffixHash: true
images:
  - name: thorax/erigon
    newTag: latest
  - name: consensys/teku
    newTag: latest