apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lighthouse
  namespace: erigon-lighthouse-ceph

spec:
  selector:
    matchLabels:
      app: lighthouse
  serviceName: lighthouse
  template:
    metadata:
      labels:
        app: lighthouse
    spec:
      terminationGracePeriodSeconds: 300
      containers:
        - name: beacon
          image: sigp/lighthouse
          args:
            - lighthouse 
            - bn
            - --network=goerli
            - --checkpoint-sync-url=https://goerli.checkpoint-sync.ethdevops.io
            - --execution-endpoint=http://erigon-svc.erigon-lighthouse-ceph.svc.cluster.local:8551
            - --execution-jwt=/opt/jwt/jwt.hex
            - --datadir=/opt/app/beacon/
            - --debug-level=info
            - --purge-db
            - --http
            - --http-address=0.0.0.0
            - --builder=http://mev-boost.erigon-lighthouse-ceph.svc.cluster.local:18550
            - --http-port=5052
            - --externalcl
          ports:
            - containerPort: 5054
              name: metrics
            - containerPort: 9000
              name: p2ptcp
            - containerPort: 9000
              protocol: UDP
              name: p2pudp
          readinessProbe:
            tcpSocket:
              port: 9000
          livenessProbe:
            tcpSocket:
              port: 9000
          startupProbe:
            failureThreshold: 60
            tcpSocket:
              port: 9000
          resources:
            limits:
              cpu: 8000m
              memory: 16G
            requests:
              cpu: 1000m
              memory: 4G
          volumeMounts:
            - mountPath: /opt/app/beacon/
              name: chaindata
            - mountPath: /opt/jwt/
              name: gethjwt
      volumes:
        - name: chaindata
          persistentVolumeClaim:
            claimName: cl 

        - configMap:
            name: erigon-jwt
          name: gethjwt
