kind: Deployment
apiVersion: apps/v1
metadata:
  name: mev-boost
  namespace: erigon-lighthouse-ceph-block
  labels:
    app: mev-boost
  annotations:
    deployment.kubernetes.io/revision: '7'
    kubesphere.io/creator: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mev-boost
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mev-boost
      annotations:
        kubesphere.io/creator: admin
    spec:
      containers:
        - name: container-ml6rxe
          image: 'flashbots/mev-boost:1.4.0'
          command:
            - /app/mev-boost
            - '-loglevel'
            - debug
            - '-addr'
            - '0.0.0.0:18550'
            - '-relays'
            - >-
              https://0x8f7b17a74569b7a57e9bdafd2e159380759f5dc3ccbd4bf600414147e8c4e1dc6ebada83c0139ac15850eb6c975e82d0@builder-relay-goerli.blocknative.com,https://0xafa4c6985aa049fb79dd37010438cfebeb0f2bd42b115b89dd678dab0670c1de38da0c4e9138c9290a398ecd9a0b3110@boost-relay-goerli.flashbots.net
            - '-goerli'
            - '-relay-check'
          ports:
            - name: tcp-18550
              containerPort: 18550
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: default
      serviceAccount: default
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

  