apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: erigon-node-pvc
  namespace: erigon-lighthouse-ceph
  labels:
    app: erigon-node 
spec:
  storageClassName: ergion-lighthouse-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi