apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: erigon-node-pvc
  namespace: 
  labels:
    app: erigon-node 
spec:
  storageClassName: erigon-lighthouse-ceph-block
                    
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi