apiVersion: v1
kind: Service
metadata:
  name: nethermind
spec:
  ports:
    - protocol: TCP
      targetPort: 8545
      port: 8545
      name: http
    - protocol: TCP
      targetPort: 8551
      port: 8551
      name: authrpc
  selector:
    app: nethermind
  type: ClusterIP